### ISSUE TITLE
Hard-coded Wordle list has been changed by NYT

### ISSUE THREAD

**Issue by sejaldua** [gdold/WordleBot#4]
Hi there,

It appears that the NYT has removed all "offensive", "insensitive", and "obscure" words from their hard-coded Wordle list. It would be awesome if you could update the `wordles` list within `wordle_dictionary.py` to use the NYT hard-coded list (NOTE: this can still be found by inspecting the source code).

Cheers!

**Comment by gdold** [comment]
Fixed in commit 297764cc8bb88796a8031b57784ec8a130525b1c

New version 0.2.1 [uploaded to PyPi](https://pypi.org/project/wordlesolver/).
